In [ ]:
import numpy as np

In [7]:
print("==========Student's Performance==========")

students = np.array([
    [95,65,85],
    [89,72,88],
    [92,75,91]
])

print("\nAll Marks:")
print(students)


print("\nShape:", students.shape)

print('\n=========CLASS STATISTICS=========')

print("\nTotal Marks:", students.sum())
print("Class Average:", students.mean())
print("Highest Marks:", students.max())
print("Lowest Marks:" , students.min())

print("\n==========STUDENT'S PERCENTAGE==========")

student_avegrage = students.mean(axis=1)

print("\nStudent A Percentage:", student_avegrage[0])
print("Student B Percentage:", student_avegrage[1])
print("Student C Percentage:", student_avegrage[2])

print("\n============SUBJECT-WISE AVERAGE============")

subject_average = students.mean(axis = 0)

print("\nSubject A:", subject_average[0])
print("Subject B:", subject_average[1])
print("Subject C:", subject_average[2])

print("\n=======Topper=======")

topper = np.argmax(student_avegrage)

print("\nTopper's Student Index:", topper)
print("Topper's percentage:", student_avegrage[topper])



==========Student's Performance==========

All Marks:
[[95 65 85]
 [89 72 88]
 [92 75 91]]

Shape: (3, 3)

=========CLASS STATISTICS=========

Total Marks: 752
Class Average: 83.55555555555556
Highest Marks: 95
Lowest Marks: 65

==========STUDENT'S PERCENTAGE==========

Student A Percentage: 81.66666666666667
Student B Percentage: 83.0
Student C Percentage: 86.0

============SUBJECT-WISE AVERAGE============

Subject A: 92.0
Subject B: 70.66666666666667
Subject C: 88.0

=======Topper=======

Topper's Student Index: 2
Topper's percentage: 86.0
